before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true

tools:
    php_code_coverage:
        enabled: true
        test_command: ./vendor/bin/phpunit
    php_code_sniffer:
        enabled: true
        config:
            standard: ruleset.xml
        filter:
            paths: ["src/*", "Tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["Tests", "vendor"]
    php_loc:
        enabled: true
        excluded_dirs: ["Tests", "vendor"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/*"]