polar:
  auth:
    username: your@email.com
    password: your-password
  timezone: "Europe/Berlin"
endomondo:
  auth:
    username: your@email.com
    password: your-password
    token: XXXXXXXXXXXXXXXXX # If you have a token set it here to skip the token fetching. If you do not know your token leave field empty.
  timezone: "Europe/Berlin"
