polar:
  auth:
    username: your@email.com
    password: your-password
  timezone: "Europe/Berlin"
endomondo:
  auth:
    username: your@email.com
    password: your-password
  timezone: "Europe/Berlin"